export const pagesRoutes: any[] = [
    {
      id: 2,
      index: true,
      pageName: 'Dashboard',
      pageType: 'Static',
      entityType: 'Web',
      path: '/dashboard',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      // icon:'<LiaPuzzlePieceSolid />',
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
    },
    {
      id: 3,
      index: true,
      pageName: 'Alerts',
      pageType: 'Static',
      entityType: 'Web',
      path: '/alerts',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 4,
      index: true,
      pageName: 'Assets',
      pageType: 'Static',
      entityType: 'Web',
      path: '/assets',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 5,
      index: true,
      pageName: 'Lists',
      pageType: 'Static',
      entityType: 'Web',
      path: '/lists',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 6,
      index: true,
      pageName: 'Reports',
      pageType: 'Static',
      entityType: 'Web',
      path: '/reports',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 7,
      index: true,
      pageName: 'Tools',
      pageType: 'Static',
      entityType: 'Web',
      path: '/tools',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 8,
      index: true,
      pageName: 'Advanced',
      pageType: 'Static',
      entityType: 'Web',
      path: '/advanced',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 9,
      index: true,
      pageName: 'SetUp',
      pageType: 'Static',
      entityType: 'Web',
      path: '/setup',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },
    {
      id: 2,
      index: true,
      pageName: 'Help/Support',
      pageType: 'Static',
      entityType: 'Web',
      path: '/help',
      description: 'This is the client of the website.',
      isEnabled: 1,
      isActive: true,
      createdOn: '2024-03-17',
      updatedOn: '2024-03-17',
      createdBy: 'Admin',
      updatedBy: 'Admin',
      arrow:true,

    },

    
    
  ]
  