
 export const EmployeePerson = [
    {
      id: 1,
      fieldName: 'Full Name',
      name: 'fullName',
      isVisible: "visible",
      isRequired: true,
      description: 'Full name of the person / employee.',
      example: 'John Doe',
      option: [{id: 1,value: 'yes',},],
    },
    {
      id: 2,
      fieldName: 'Email',
      name: "email",
      isVisible: 'visible',
      isRequired: false,
      
      description: 'Email of the person',
      example: 'johndoe@example.com',
      option: [{ id: 1, value: 'yes', }, { id: 2, value: 'optional', }, ],
    },
    {
      id: 3,
      fieldName: 'Employee ID',
      name: "employeeID",
      isVisible: 'visible',
      isRequired: false,
      description: 'For example Employee ID, Student ID, etc.',
      example: 'IT-1234',
      option: [{ id: 1, value: 'yes' },  { id: 2, value: 'optional', }, ],
    },
    {
      id: 4,
      fieldName: 'Title',
      name: "title",
      isVisible: 'visible',
      isRequired: false,
      description: '  fieldName of the person.',
      example: '  Sales Manager',
      option: [ {  id: 1, value: 'yes',  }, { id: 2,  value: 'optional', }, ],
    },
    {
      id: 5,
      fieldName: 'Phone',
      name: "phone",
      isVisible: 'visible',
      isRequired: false,    
      description: 'Phone number of the person',
      example: '(555) 123-4567',
      option: [ {  id: 1,  value: 'yes',  }, { id: 2, value: 'optional',  }, ],
    },
    {
      id: 6,
      fieldName: 'Notes',
      name: "notes",
      isVisible: 'visible',
      isRequired: false,
      description: 'Text area for notes',
      example: 'Reports to CEO',
      option: [ { id: 1, value: 'yes',  }, {  id: 2,  value: 'optional', }, ],
    },
    {
      id: 7,
      fieldName: 'Site',
      name: "site",
      isVisible: 'visible',
      isRequired: false,
      description: 'System field to link person to a Site',
      example: '-',
      option: [  { id: 1, value: 'yes', }, { id: 2, value: 'optional',  },],
    },
    {
      id: 8,
      fieldName: 'Location',
      name: "location",
      isVisible: 'visible',
      isRequired: false,
      description: 'System field to link person to a Location',
      example: '  -',
      option: [  { id: 1, value: 'yes', }, { id: 2, value: 'optional', }, ],
    },
    {
      id: 9,
      fieldName: 'Department',
      name: "department",
      isVisible: 'visible',
      isRequired: false,
      description: '  System field to link person to a Department',
      example: '  -',
      option: [{ id: 1, value: 'yes', }, { id: 2, value: 'optional', },],
    },
  ]

  export const empData = [
    {
      isVisible: true,
      fieldName: 'Full Name',
      name: 'fullName',
      description: 'string',
      isRequired: true,
    },
    {
        visible: true,
        fieldName: "Email",
        name: "email",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Employee ID",
        name: "employeeID",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Title",
        name: "title",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Phone",
        name: "phone",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Notes",
        name: "notes",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Site",
        name: "site",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Location",
        name: "location",
        isRequired: false,
        description: "string",
    },
    {
        visible: true,
        fieldName: "Department",
        name: "department",
        isRequired: false,
        description: "string",
    },

]