jobs:
  eks-deployment:
    runs-on: ubuntu-latest
    needs: docker-ecr  # This ensures the EKS job runs after the docker-ecr job

    steps:
      # Step 1: Set up AWS credentials for EKS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 2: Install kubectl
      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.26.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Step 3: Update kubeconfig for EKS
      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      # Step 4: Apply Deployment to EKS
      - name: Deploy to EKS
        run: |
          kubectl apply -f .github/workflows/deployment.yaml  # Updated path
          kubectl rollout status deployment/asset-management-ui  # Ensure the deployment is successful
