name: CI/CD Pipeline with Docker and SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker username from GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker PAT from GitHub secrets

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t nagarajkhairate/asset-management-ui:${{ github.sha }} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push nagarajkhairate/asset-management-ui:${{ github.sha }}

      # Step 5: Pull the Docker image from Docker Hub (optional, to verify the push)
      - name: Pull Docker Image from Docker Hub
        run: docker pull nagarajkhairate/asset-management-ui:${{ github.sha }}

      # Optional: Run Docker container to test the pushed image
      - name: Run Docker Container (optional)
        run: |
          docker run -d --name test-container nagarajkhairate/asset-management-ui:${{ github.sha }}
          docker ps

  approval:
    runs-on: ubuntu-latest
    needs: docker  # This ensures this job runs after the 'docker' job

    environment:
      name: production  # Use a specific environment for approval

    steps:
      - name: Request approval to proceed
        run: |
          echo "Waiting for manual approval to proceed with deployment..."

