name: Docker Build, Push, and Pull

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image
      - name: Build Docker Image
        run: docker build -t yourdockerhubusername/asset-management-ui:${{ github.sha }} .

      # Step 4: Push the Docker image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: docker push yourdockerhubusername/asset-management-ui:${{ github.sha }}

      # Step 5: Pull the Docker image from Docker Hub (optional, to verify the push)
      - name: Pull Docker Image from Docker Hub
        run: docker pull yourdockerhubusername/asset-management-ui:${{ github.sha }}

      # Optional: Verify the image (e.g., run a container from the pulled image)
      - name: Run Docker Container (optional)
        run: |
          docker run -d --name test-container yourdockerhubusername/asset-management-ui:${{ github.sha }}
          docker ps
