name: CI/CD Pipeline with Manual Approvals

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t yourdockerhubusername/asset-management-ui .

      - name: Push Docker Image
        run: docker push yourdockerhubusername/asset-management-ui

  test:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testing
    steps:
      - name: Wait for Manual Approval for Testing
        uses: actions/manual@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Testing Environment
        run: |
          echo "Deploying to Testing Environment"
          # Add your testing deployment steps here

  staging:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: staging
    steps:
      - name: Wait for Manual Approval for Staging
        uses: actions/manual@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Staging Environment
        run: |
          echo "Deploying to Staging Environment"
          # Add your staging deployment steps here

  production:
    runs-on: ubuntu-latest
    needs: staging
    environment:
      name: production
    steps:
      - name: Wait for Manual Approval for Production
        uses: actions/manual@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Production Environment
        run: |
          echo "Deploying to Production Environment"
          # Add your production deployment steps here
