name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Elasticsearch
      uses: elastic/elastic-github-actions@v1
      with:
        elasticsearch-version: '7.10.1'

    - name: Build and Test
      run: |
        ./gradlew build
        ./gradlew test

    - name: Deploy to Server
      run: |
        scp -r * user@your-server:/path/to/deploy
        ssh user@your-server 'bash /path/to/deploy/deploy.sh'
