name: Build and SonarQube Scan

on:
  push:
    branches:
      - main  # Set your branch here
  pull_request:
    branches:
      - main  # Set your branch here

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner you want

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install  # If you're using npm, use the corresponding package manager

      # Step 3: Install Java (dependency for SonarScanner)
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      # Step 4: Install SonarScanner via apt (alternative method)
      - name: Install SonarScanner
        run: |
          # Add SonarSource repository for SonarScanner
          curl -sL https://deb.sonarsource.com/sonarscanner/sonarscanner-apt-key.asc | sudo apt-key add -
          echo "deb https://deb.sonarsource.com/sonarscanner/apt stable main" | sudo tee /etc/apt/sources.list.d/sonarsource.list
          sudo apt-get update
          sudo apt-get install sonar-scanner

      # Step 5: Run SonarQube scan
      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
