name: Build and SonarQube Scan

on:
  push:
    branches:
      - main  # Set your branch here
  pull_request:
    branches:
      - main  # Set your branch here

jobs:
  build:
    runs-on: ubuntu-latest  # Specify the runner you want

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install  # If you're using npm, use the corresponding package manager

      # Step 3: Install Java (dependency for SonarScanner)
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk

      # Step 4: Install SonarScanner via direct download
      - name: Download and install SonarScanner
        run: |
          # Download SonarScanner
          wget https://github.com/SonarSource/sonar-scanner-cli/releases/download/4.8.0.2856/sonar-scanner-cli-4.8.0.2856-linux.zip
          
          # Unzip and move it to the proper directory
          unzip sonar-scanner-cli-4.8.0.2856-linux.zip
          sudo mv sonar-scanner-4.8.0.2856-linux /opt/sonar-scanner

          # Add SonarScanner to the PATH
          echo 'export PATH=$PATH:/opt/sonar-scanner/bin' >> ~/.bashrc
          source ~/.bashrc

      # Step 5: Run SonarQube scan
      - name: Run SonarQube scan
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
