name: Build and SonarQube Scan

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install project dependencies (e.g., npm for Node.js projects)
      - name: Install dependencies
        run: |
          npm install  # Adjust this line if you are using a different package manager (e.g., yarn)

      # Step 3: Set up Docker to run the SonarScanner container
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx for cross-platform builds

      # Step 4: Run SonarQube scan using Docker
      - name: Run SonarQube scan with Docker
        run: |
          docker run --rm \
            -v $(pwd):/usr/src \
            -e SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }} \
            -e SONAR_LOGIN=${{ secrets.SONAR_TOKEN }} \
            sonarsource/sonar-scanner-cli:latest \
            sonar-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.sources=src  # Adjust this line based on the location of your source code
